### ISSUE TITLE
Неоправданное использование хеш-таблицы для результатов

### ISSUE THREAD

**Issue by vporoshok** [lohnes66/elma_and_rostelecom_bpm_test_task#1]
При большом количестве входных данных хранение по каналу на каждый запрос, да ещё и в хеш-таблицы дают по 64*3 (канал) + 64*2 (ключ с фактором 0.5 в хеш-таблице) = 320 байт на каждый входной url, что несколько неоправданно. Можно ли как-то формировать сумму по мере обработки запросов, не накапливая данные?

**Comment by lohnes66** [comment]
Поленился немного, каюсь :-)
Добавил гроутину для подсчета итоговой суммы.
